### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Jorybraun** [PolymerX/lit-loader#1]
How does this work with SVG from lit-html?

**Comment by LasaleFamine** [comment]
Hi @Jorybraun, actually I think this should work out of the box with some Webpack loaders of SVG. Did you try something yet?

**Comment by equinusocio** [comment]
@Jorybraun do you mean external svg images (`<img src="---.svg" />`) or inlined `<svg></svg>`?

**Comment by Jorybraun** [comment]
honestly forget sorry @equinusocio
